---
name: aida
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
volumes:
  signal-data:
    labels:
      com.aida.description: "Signal storage volume"
  mongo-data:
    labels:
      com.aida.description: "MongoDB storage volume"
services:
  signal:
    # https://bbernhard.github.io/signal-cli-rest-api/
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal
    restart: always
    environment:
      MODE: json-rpc
      PORT: 1337
    ports:
      - "1337:1337"
    # healthcheck to http://localhost:1337/v1/health
    # register: http://localhost:1337/v1/qrcodelink?device_name=aida
    volumes:
      - signal-data:/home/.local/share/signal-cli
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_DISABLE_TELEMETRY: 1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: password
      #ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
...
